org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

curseforgeId=1056828
modrinthId=2oORTOi2

# Forestry
forestryVersion=2.6.1

# Minecraft
minecraftVersion=1.21.1
mappingsVersion=2024.11.17
# Forge
neoForgeVersion=21.1.172
forgeVersionRange=[21.1,)
fmlVersionRange=[4,)
# JEI
jeiVersion=19.19.6.236
jeiVersionRange=[19,)
# Patchouli
patchouliVersion=1.21-88
patchouliVersionRange=[1.21-88,)
# KubeJS
kubejs_version=2101.7.1-build.181
rhino_version=2101.2.7-build.74
architectury_version=13.0.8
# Curios
curiosVersion=9.5.1
